= CalConnect Directive: Standard document requirements
:repo-owner: CalConnect
:repo-name: csd-directive-document-requirements


This work item belongs to TC CALSPAM.

image:https://travis-ci.com/CalConnect/csd-directive-document-requirements.svg?branch=master["Build Status", link="https://travis-ci.com/CalConnect/csd-directive-document-requirements"]

This document is available in its rendered forms here:

* https://CalConnect.github.io/csd-directive-document-requirements/[CalConnect Directive: Standard document requirements (HTML)]
* https://CalConnect.github.io/csd-directive-document-requirements/csd-directive-document-requirements.pdf[PDF]
* https://CalConnect.github.io/csd-directive-document-requirements/csd-directive-document-requirements.xml[Metanorma XML]
* https://CalConnect.github.io/csd-directive-document-requirements/csd-directive-document-requirements.rxl[Relaton XML (Bibliographic item)]

Because of all this, there is no need to build the document on your own, but if you wish to do so, this is how it can be done:

== Fetching the document

[source,sh]
----
git clone https://gitlab.com/CalConnect/csd-directive-document-requirements/
----

== Installing Build Tools

See https://www.metanorma.com/overview/getting-started/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make clean all
----

The following outputs will be built:

* CSD XML (https://github.com/calconnect/metanorma-model-csd) (`[filename].xml`)
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make html
open csd-*.html
----

